### ISSUE TITLE
Why data matrix should be N_samples x N_features

### ISSUE THREAD

**Issue by anlijuncn** [rpomponio/neuroHarmonize#1]
Hi Pomponio, 
I am Lijun, a PhD student from NUS. 
I am trying to use neuroHarmonize package, and I am a little confused why data matrix should be N_samples x N_features. 
For example, if I am interested in ['hippocampus', 'ventricles'], and I have 1000 subjects from 2 sites, shouldn't I feed a 1000x2 data matrix?
Thanks for your help!

**Comment by rpomponio** [comment]
Hi Lijun!

You are correct that the data matrix should be 1000x2, if you have 1,000 subjects in total and 2 features to harmonize. In this case the two features are hippocampus and ventricles.

In a separate data-frame, called "covars" in my example, you provide a column called "SITE" which indicates the site that each subject came from. The covars data will have 1,000 rows as well.

Hope this helps and happy to discuss further.

**Comment by anlijuncn** [comment]
Hi Pomponio, 

Thanks for your reply! It helps me a lot, I am python user, so the ComBat python version is much easier for me to use. Excellent work for your ComBat-GAM!
