### ISSUE TITLE
How many subjects per scanner are required?

### ISSUE THREAD

**Issue by Melissa1909** [rpomponio/neuroHarmonize#34]
Dear Raymond,
thanks for providing this awesome repo! 

I was wondering how many subjects are necessary to get substantial estimations for the scanner effect? I've read this post (https://github.com/rpomponio/neuroHarmonize/issues/16) and have seen your response saying that fitting the model on healthy controls alone would make sense and that the amount has to be large enough. What would you consider "large enough"? I'd have a dataset with 4 sites (n(HC)=140), with one of them having only 25 healthy controls. 
Best, Melissa

**Comment by rpomponio** [comment]
I'm not aware of a consensus threshold for the amount of subjects needed per site in harmonization, but 25 Healthy Controls is near the lower-limit, especially if you are including multiple covariates (age, sex, etc.).

The empirical Bayes step should mitigate small sample effects by shrinking the site effects towards the pooled mean. It would be interesting to see results with and without EB.

Closing this issue for now, but feel free to open with additional comments.
