### ISSUE TITLE
Cropped images

### ISSUE THREAD

**Issue by SPChytas** [rpomponio/neuroHarmonize#37]
Hello, and congratulations for the nice codebase. 
I am trying to use the NeuroHarmonize for the Nifti images, however I get a very weird performance in some cases. I have a dataset of more than 1000 images and after applying the NeuroHarmonize following all the steps of your README, I end up with cropped images, like the ones in the attached file (left is the original, right after NeuroHarmonize).
![Screenshot from 2023-08-14 18-06-32](https://github.com/rpomponio/neuroHarmonize/assets/26147058/c6d060ab-b405-46ae-969e-4d50578b11fd)

**Comment by rpomponio** [comment]
Related to #40 , this method is not equipped to harmonize raw images. Must register images to a template space and provide pre-processed NIFTIs.
